### ISSUE TITLE
Android APK not available for download

### ISSUE THREAD

**Issue by somethingp** [snuq/Snu-Photo-Manager#11]
Linux and Windows executables are there, but no Android APK.

**Comment by snuq** [comment]
Ive had some trouble getting all the libraries working on android, newer android versions have much more complex file permissions that ill need to figure out, and google has started requiring a different format from apk that I'm not sure if the toolchain I use even supports yet... unfortunately, because of these difficulties, I have not even thought about the android version for quite a while, and right now I'm not sure when I will get back to it.

**Comment by somethingp** [comment]
Thanks that's too bad. I was originally looking for a solution for easy SD card to hard drive backup using my phone with a photo database. I started looking into just making a app, but the permissions seemed crazy. I was hoping you had figured it out and had a working solution haha. I'll just stick to copy and pasting with a file manager app.
