### ISSUE TITLE
When downloading the apk file the link opens in to a webpage

### ISSUE THREAD

**Issue by guysoft** [snuq/Snu-Photo-Manager#3]
When you click on the android apk file in the "download" page you get lots of gibberish and not the app. Which requited fiddeling to download.

Perhaps you should change the apache settings, or better still upload the package to f-droid.org?

**Comment by snuq** [comment]
Well, the android version is definitely not ready for release, it has a couple pretty big bugs and missing features that I do not currently know how to get past.  So, until it is fully functional, I wont be releasing it on f-droid or play store.

As for the download not working right, you can always right click the file and 'save as' (or similar depending on your browser), but im really not sure of any server settings to make it just download... In fact, vivaldi (chrome variant) seems to download it fine, while firefox tries to open it, so it may be a browser setting rather than a server thing.

**Comment by guysoft** [comment]
You could upload it to tags when you release: https://github.com/snuq/Snu-Photo-Manager/releases
BTW I am starting to play with a simple gallery using kivy for ownphotos.

**Comment by snuq** [comment]
I updated the readme with some better installation instructions, including a warning that the files may need to be right clicked and 'save as'.  For now, this is all I can do to alleviate this I think.
